# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bogdanof/algo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bogdanof/algo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bogdanof/algo/CMakeFiles /home/bogdanof/algo/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bogdanof/algo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named contrib_catch_main

# Build rule for target.
contrib_catch_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 contrib_catch_main
.PHONY : contrib_catch_main

# fast build rule for target.
contrib_catch_main/fast:
	$(MAKE) -f CMakeFiles/contrib_catch_main.dir/build.make CMakeFiles/contrib_catch_main.dir/build
.PHONY : contrib_catch_main/fast

#=============================================================================
# Target rules for targets named test-all

# Build rule for target.
test-all: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-all
.PHONY : test-all

# fast build rule for target.
test-all/fast:
	$(MAKE) -f CMakeFiles/test-all.dir/build.make CMakeFiles/test-all.dir/build
.PHONY : test-all/fast

#=============================================================================
# Target rules for targets named bin/graph

# Build rule for target.
bin/graph: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin/graph
.PHONY : bin/graph

# fast build rule for target.
bin/graph/fast:
	$(MAKE) -f graph/graph/CMakeFiles/bin/graph.dir/build.make graph/graph/CMakeFiles/bin/graph.dir/build
.PHONY : bin/graph/fast

#=============================================================================
# Target rules for targets named custom_graph

# Build rule for target.
custom_graph: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 custom_graph
.PHONY : custom_graph

# fast build rule for target.
custom_graph/fast:
	$(MAKE) -f graph/graph/CMakeFiles/custom_graph.dir/build.make graph/graph/CMakeFiles/custom_graph.dir/build
.PHONY : custom_graph/fast

#=============================================================================
# Target rules for targets named bin/prim_algorithm

# Build rule for target.
bin/prim_algorithm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin/prim_algorithm
.PHONY : bin/prim_algorithm

# fast build rule for target.
bin/prim_algorithm/fast:
	$(MAKE) -f graph/mst/prim_algorithm/CMakeFiles/bin/prim_algorithm.dir/build.make graph/mst/prim_algorithm/CMakeFiles/bin/prim_algorithm.dir/build
.PHONY : bin/prim_algorithm/fast

#=============================================================================
# Target rules for targets named bin/integer_log

# Build rule for target.
bin/integer_log: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin/integer_log
.PHONY : bin/integer_log

# fast build rule for target.
bin/integer_log/fast:
	$(MAKE) -f math/lib/integer_log/CMakeFiles/bin/integer_log.dir/build.make math/lib/integer_log/CMakeFiles/bin/integer_log.dir/build
.PHONY : bin/integer_log/fast

#=============================================================================
# Target rules for targets named integer_log

# Build rule for target.
integer_log: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 integer_log
.PHONY : integer_log

# fast build rule for target.
integer_log/fast:
	$(MAKE) -f math/lib/integer_log/CMakeFiles/integer_log.dir/build.make math/lib/integer_log/CMakeFiles/integer_log.dir/build
.PHONY : integer_log/fast

#=============================================================================
# Target rules for targets named bin/max_edge_up_to_lca

# Build rule for target.
bin/max_edge_up_to_lca: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin/max_edge_up_to_lca
.PHONY : bin/max_edge_up_to_lca

# fast build rule for target.
bin/max_edge_up_to_lca/fast:
	$(MAKE) -f graph/lca/max_edge_up_to_lca/CMakeFiles/bin/max_edge_up_to_lca.dir/build.make graph/lca/max_edge_up_to_lca/CMakeFiles/bin/max_edge_up_to_lca.dir/build
.PHONY : bin/max_edge_up_to_lca/fast

#=============================================================================
# Target rules for targets named max_edge_up_to_lca

# Build rule for target.
max_edge_up_to_lca: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 max_edge_up_to_lca
.PHONY : max_edge_up_to_lca

# fast build rule for target.
max_edge_up_to_lca/fast:
	$(MAKE) -f graph/lca/max_edge_up_to_lca/CMakeFiles/max_edge_up_to_lca.dir/build.make graph/lca/max_edge_up_to_lca/CMakeFiles/max_edge_up_to_lca.dir/build
.PHONY : max_edge_up_to_lca/fast

#=============================================================================
# Target rules for targets named bin/comp_long_numbers

# Build rule for target.
bin/comp_long_numbers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin/comp_long_numbers
.PHONY : bin/comp_long_numbers

# fast build rule for target.
bin/comp_long_numbers/fast:
	$(MAKE) -f unk/comp_long_numbers/CMakeFiles/bin/comp_long_numbers.dir/build.make unk/comp_long_numbers/CMakeFiles/bin/comp_long_numbers.dir/build
.PHONY : bin/comp_long_numbers/fast

#=============================================================================
# Target rules for targets named bin/dinner_with_natasha

# Build rule for target.
bin/dinner_with_natasha: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin/dinner_with_natasha
.PHONY : bin/dinner_with_natasha

# fast build rule for target.
bin/dinner_with_natasha/fast:
	$(MAKE) -f unk/dinner_with_natasha/CMakeFiles/bin/dinner_with_natasha.dir/build.make unk/dinner_with_natasha/CMakeFiles/bin/dinner_with_natasha.dir/build
.PHONY : bin/dinner_with_natasha/fast

#=============================================================================
# Target rules for targets named bin/labyrinth

# Build rule for target.
bin/labyrinth: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin/labyrinth
.PHONY : bin/labyrinth

# fast build rule for target.
bin/labyrinth/fast:
	$(MAKE) -f unk/labyrinth/CMakeFiles/bin/labyrinth.dir/build.make unk/labyrinth/CMakeFiles/bin/labyrinth.dir/build
.PHONY : bin/labyrinth/fast

#=============================================================================
# Target rules for targets named bin/longest_k_good_segment

# Build rule for target.
bin/longest_k_good_segment: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin/longest_k_good_segment
.PHONY : bin/longest_k_good_segment

# fast build rule for target.
bin/longest_k_good_segment/fast:
	$(MAKE) -f two-pointers/longest_k_good_segment/CMakeFiles/bin/longest_k_good_segment.dir/build.make two-pointers/longest_k_good_segment/CMakeFiles/bin/longest_k_good_segment.dir/build
.PHONY : bin/longest_k_good_segment/fast

tools/catch/catch_main.o: tools/catch/catch_main.cpp.o
.PHONY : tools/catch/catch_main.o

# target to build an object file
tools/catch/catch_main.cpp.o:
	$(MAKE) -f CMakeFiles/contrib_catch_main.dir/build.make CMakeFiles/contrib_catch_main.dir/tools/catch/catch_main.cpp.o
.PHONY : tools/catch/catch_main.cpp.o

tools/catch/catch_main.i: tools/catch/catch_main.cpp.i
.PHONY : tools/catch/catch_main.i

# target to preprocess a source file
tools/catch/catch_main.cpp.i:
	$(MAKE) -f CMakeFiles/contrib_catch_main.dir/build.make CMakeFiles/contrib_catch_main.dir/tools/catch/catch_main.cpp.i
.PHONY : tools/catch/catch_main.cpp.i

tools/catch/catch_main.s: tools/catch/catch_main.cpp.s
.PHONY : tools/catch/catch_main.s

# target to generate assembly for a file
tools/catch/catch_main.cpp.s:
	$(MAKE) -f CMakeFiles/contrib_catch_main.dir/build.make CMakeFiles/contrib_catch_main.dir/tools/catch/catch_main.cpp.s
.PHONY : tools/catch/catch_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... contrib_catch_main"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test-all"
	@echo "... bin/graph"
	@echo "... custom_graph"
	@echo "... bin/prim_algorithm"
	@echo "... bin/integer_log"
	@echo "... integer_log"
	@echo "... bin/max_edge_up_to_lca"
	@echo "... max_edge_up_to_lca"
	@echo "... bin/comp_long_numbers"
	@echo "... bin/dinner_with_natasha"
	@echo "... bin/labyrinth"
	@echo "... bin/longest_k_good_segment"
	@echo "... tools/catch/catch_main.o"
	@echo "... tools/catch/catch_main.i"
	@echo "... tools/catch/catch_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

